apiVersion: argoproj.io/v1alpha1
kind: Kustomization
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: podinfo
  source:
    name: podinfo-deployment-localized
    repoURL: oci://ghcr.io/github.com/mohammad-ammar14/argo-ocm.git
    # #https://charts.karpenter.sh/
  # source:
  #   repoURL: https://github.com/mohammad-ammar14/argo-ocm.git
  #   name: podinfo-deployment-localized
  # path: ./  
    # #https://charts.karpenter.sh/
# apiVersion: argoproj.io/v1alpha1
# kind: Kustomization
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   interval: 1m0s
#   prune: true
#   targetNamespace: default
#   sourceRef:
#     kind: OCIRepository
#     name: podinfo-deployment-localized
#   path: ./