project: default
source:
  repoURL: oci://ghcr.io/mohammad-ammar14/backend-chart:0.1.0
  targetRevision: 12.1.3
  chart: backend-chart
destination:
  server: https://kubernetes.default.svc
syncPolicy:
  automated: {}
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: podinfo
#   namespace: argocd
# spec:
#   destination:
#     namespace: default
#     server: https://kubernetes.default.svc
#   project: podinfo
#   source:
#     name: podinfo-deployment-localized
#    repoURL: oci://ghcr.io/github.com/mohammad-ammar14/argo-ocm
    # #https://charts.karpenter.sh/
  # source:
  #   repoURL: https://github.com/mohammad-ammar14/argo-ocm.git
  #   name: podinfo-deployment-localized
  # path: ./  
    # #https://charts.karpenter.sh/
# apiVersion: argoproj.io/v1alpha1
# kind: Kustomization
# metadata:
#   name: podinfo
#   namespace: default
# spec:
#   interval: 1m0s
#   prune: true
#   targetNamespace: default
#   sourceRef:
#     kind: OCIRepository
#     name: podinfo-deployment-localized
#   path: ./