apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podinfo-deployment-localized



# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: podinfo
#   namespace: argocd
# spec:
#   interval: 1m0s
#   prune: true
#   targetNamespace: default
#   sourceRef:
#     kind: OCIRepository
#     name: podinfo-deployment-localized
#   path: ./
